/// <reference types="react/next" />
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited. This file is auto-generated by Tailwind CSS.
// Learn more at https://tailwindcss.com/docs/typescript#intellisense

declare module "*.css" {
  const content: string;
  export default content;
}

declare module "*.png" {
  const content: string;
  export default content;
}

declare module "*.svg" {
  const content: string;
  export default content;
}

declare module "*.jpg" {
  const content: string;
  export default content;
}

declare module "*.jpeg" {
  const content: string;
  export default content;
}

